export const DELIVERY_PACKAGES_ADD = 'DELIVERY_PACKAGES_ADD';
export const DELIVERY_PACKAGES_ALL = 'DELIVERY_PACKAGES_ALL';
export const DELIVERY_PACKAGES_ONE = 'DELIVERY_PACKAGES_ONE';
export const DELIVERY_PACKAGES_ONE_SELECTED = 'DELIVERY_PACKAGES_ONE_SELECTED';
export const DELIVERY_PACKAGE_UPDATE = 'DELIVERY_PACKAGE_UPDATE';
export const DELIVERY_PACKAGE_DELETE = 'DELIVERY_PACKAGE_DELETE';
