export const DELIVERY_COMPANIES_ADD = 'DELIVERY_COMPANIES_ADD';
export const DELIVERY_COMPANIES_ALL = 'DELIVERY_COMPANIES_ALL';
export const DELIVERY_COMPANIES_ONE = 'DELIVERY_COMPANIES_ONE';
export const DELIVERY_COMPANIES_ONE_SELECTED = 'DELIVERY_COMPANIES_ONE_SELECTED';
export const DELIVERY_COMPANY_UPDATE = 'DELIVERY_COMPANY_UPDATE';
export const DELIVERY_COMPANY_DELETE = 'DELIVERY_COMPANY_DELETE';
