export const NOTIFICATIONS_ALL = 'NOTIFICATIONS_ALL';
export const NOTIFICATIONS_ONE_SELECTED = 'NOTIFICATIONS_ONE_SELECTED';
export const NOTIFICATION_MARK_AS_READ = 'NOTIFICATION_MARK_AS_READ';
export const NOTIFICATION_DELETE = 'NOTIFICATION_DELETE';
