export const ORDERS_ALL = 'ORDERS_ALL';
export const ORDERS_ONE = 'ORDERS_ONE';
export const ORDERS_MULTIPLE_SELECTED = 'ORDERS_MULTIPLE_SELECTED';
export const ORDER_UPDATE = 'ORDER_UPDATE';
export const ORDER_ADD = 'ORDER_ADD';
export const ORDER_DELETE = 'ORDER_DELETE';
