export const PRODUCTS_ALL = 'PRODUCTS_ALL';
export const PRODUCTS_ONE = 'PRODUCTS_ONE';
export const PRODUCTS_ONE_SELECTED = 'PRODUCTS_ONE_SELECTED';
export const PRODUCT_UPDATE = 'PRODUCT_UPDATE';
export const PRODUCT_UPDATE_MULTIPLE = 'PRODUCT_UPDATE_MULTIPLE';
export const PRODUCT_ADD = 'PRODUCT_ADD';
export const PRODUCT_DELETE = 'PRODUCT_DELETE';
