export const TESTIMONIAL_ADD = 'TESTIMONIAL_ADD';
export const TESTIMONIALS_ALL = 'TESTIMONIALS_ALL';
export const TESTIMONIALS_ONE = 'TESTIMONIALS_ONE';
export const TESTIMONIALS_ONE_SELECTED = 'TESTIMONIALS_ONE_SELECTED';
export const TESTIMONIAL_UPDATE = 'TESTIMONIAL_UPDATE';
export const TESTIMONIAL_DELETE = 'TESTIMONIAL_DELETE';
