export const TRANSACTION_ADD = 'TRANSACTION_ADD';
export const TRANSACTIONS_ALL = 'TRANSACTIONS_ALL';
export const TRANSACTION_UPDATE = 'TRANSACTION_UPDATE';
export const TRANSACTION_DELETE = 'TRANSACTION_DELETE';
export const TRANSACTIONS_ONE = 'TRANSACTIONS_ONE';
export const TRANSACTIONS_ONE_SELECTED = 'TRANSACTIONS_ONE_SELECTED';
